server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

services:
  post-service:
    url: ${POST_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, metrics
  endpoint:
    gateway:
      enabled: true